#Variável indetificação de um dado para ser utilizado depois
#len retorna a quantidade de caracteres da string

name = input('Qual o seu nome?')
print(name)

name = 'Jesus Cristo'
length = len(name) # variável length = comprimento / len para saber quantos caracteres tem na string
print(length) # aqui irá imprimir quantos caracteres tem na string

name = input('digite') # aqui pede para digitar os caracteres
length = len(name) # aqui verifica quantos caracteres tem na string digitada
print(length) # aqui imprime o valor da string da variavel length
